main:
  - name: Over
    url: "#about"
    weight: 1
  - name: Ervaring
    url: "#experience"
    weight: 2
  - name: Berichten
    url: /posts/
    weight: 3
  - name: Wereldbouw
    url: https://rutgerkok.nl/minecraft
    weight: 4
