mainSections:
  - posts
description: marijnk.nl is een beknopt CV en mijn blog over technologie, muziek en andere dingen die Marijn interesseren.
colorScheme: auto

siteType: Person
icon: images/icon.png
publisherName: Marijn Kok
publisherLogo:
math:
  handler: katex

highlight:
  handler: highlightjs

  highlightjs:
    # See https://github.com/highlightjs/cdn-release/tree/main/build/languages for available languages.
    languages:
      - bash
      - ini
      - yaml
      - json
    # See https://github.com/highlightjs/cdn-release/tree/main/build/styles for available styles.
    style: base16/solarized-light
